import type { MembershipPlan, UserMembership, MembershipAnalytics, MembershipAuditLog } from "@/lib/types/membership";

export const membershipPlans: MembershipPlan[] = [
  {
    id: "plan-silver",
    name: "Silver",
    tier: "silver",
    price: 999,
    validityDays: 365,
    maxFamilyMembers: 2,
    status: "active",
    currentVersion: 2,
    memberCount: 42180,
    createdAt: "2023-01-15",
    updatedAt: "2024-03-10",
    versions: [
      {
        version: 1,
        createdAt: "2023-01-15",
        createdBy: "Super Admin",
        changes: "Initial plan creation",
        features: [],
      },
      {
        version: 2,
        createdAt: "2024-03-10",
        createdBy: "Super Admin",
        changes: "Reduced free appointments from 6 to 4, Added AI Health Assistant",
        features: [],
      },
    ],
    features: [
      { id: "f1", name: "Free Doctor Appointments", category: "Appointments", enabled: true, quantity: 4, validityDays: 365 },
      { id: "f2", name: "Follow-up Appointments", category: "Appointments", enabled: true, quantity: 2, validityDays: 365 },
      { id: "f3", name: "Laboratory Discounts", category: "Discounts", enabled: true, percentage: 10 },
      { id: "f4", name: "Diagnostic Discounts", category: "Discounts", enabled: true, percentage: 10 },
      { id: "f5", name: "Pharmacy Discounts", category: "Discounts", enabled: true, percentage: 5 },
      { id: "f6", name: "Health Package Discounts", category: "Discounts", enabled: false },
      { id: "f7", name: "Wallet Credits", category: "Financial", enabled: true, percentage: 2 },
      { id: "f8", name: "Cashback Percentage", category: "Financial", enabled: false },
      { id: "f9", name: "Insurance Benefits", category: "Insurance", enabled: false },
      { id: "f10", name: "AI Health Assistant", category: "Digital", enabled: true, limit: 10 },
      { id: "f11", name: "Emergency Benefits", category: "Emergency", enabled: false },
      { id: "f12", name: "Priority Booking", category: "Appointments", enabled: false },
      { id: "f13", name: "Free Health Checkups", category: "Checkups", enabled: true, quantity: 1 },
      { id: "f14", name: "Referral Rewards", category: "Rewards", enabled: true, quantity: 100 },
    ],
  },
  {
    id: "plan-gold",
    name: "Gold",
    tier: "gold",
    price: 2499,
    validityDays: 365,
    maxFamilyMembers: 4,
    status: "active",
    currentVersion: 3,
    memberCount: 31490,
    createdAt: "2023-01-15",
    updatedAt: "2024-06-01",
    versions: [
      { version: 1, createdAt: "2023-01-15", createdBy: "Super Admin", changes: "Initial plan creation", features: [] },
      { version: 2, createdAt: "2023-11-20", createdBy: "Super Admin", changes: "Reduced free appointments from 12 to 8", features: [] },
      { version: 3, createdAt: "2024-06-01", createdBy: "Super Admin", changes: "Added Insurance Benefits, increased pharmacy discount to 15%", features: [] },
    ],
    features: [
      { id: "f1", name: "Free Doctor Appointments", category: "Appointments", enabled: true, quantity: 8, validityDays: 365 },
      { id: "f2", name: "Follow-up Appointments", category: "Appointments", enabled: true, quantity: 6, validityDays: 365 },
      { id: "f3", name: "Laboratory Discounts", category: "Discounts", enabled: true, percentage: 20 },
      { id: "f4", name: "Diagnostic Discounts", category: "Discounts", enabled: true, percentage: 20 },
      { id: "f5", name: "Pharmacy Discounts", category: "Discounts", enabled: true, percentage: 15 },
      { id: "f6", name: "Health Package Discounts", category: "Discounts", enabled: true, percentage: 15 },
      { id: "f7", name: "Wallet Credits", category: "Financial", enabled: true, percentage: 3 },
      { id: "f8", name: "Cashback Percentage", category: "Financial", enabled: true, percentage: 5 },
      { id: "f9", name: "Insurance Benefits", category: "Insurance", enabled: true },
      { id: "f10", name: "AI Health Assistant", category: "Digital", enabled: true, limit: 30 },
      { id: "f11", name: "Emergency Benefits", category: "Emergency", enabled: true },
      { id: "f12", name: "Priority Booking", category: "Appointments", enabled: true },
      { id: "f13", name: "Free Health Checkups", category: "Checkups", enabled: true, quantity: 2 },
      { id: "f14", name: "Referral Rewards", category: "Rewards", enabled: true, quantity: 200 },
    ],
  },
  {
    id: "plan-platinum",
    name: "Platinum",
    tier: "platinum",
    price: 4999,
    validityDays: 365,
    maxFamilyMembers: 6,
    status: "active",
    currentVersion: 1,
    memberCount: 10650,
    createdAt: "2023-06-01",
    updatedAt: "2023-06-01",
    versions: [
      { version: 1, createdAt: "2023-06-01", createdBy: "Super Admin", changes: "Initial plan creation", features: [] },
    ],
    features: [
      { id: "f1", name: "Free Doctor Appointments", category: "Appointments", enabled: true, quantity: 24, validityDays: 365 },
      { id: "f2", name: "Follow-up Appointments", category: "Appointments", enabled: true, quantity: 12, validityDays: 365 },
      { id: "f3", name: "Laboratory Discounts", category: "Discounts", enabled: true, percentage: 30 },
      { id: "f4", name: "Diagnostic Discounts", category: "Discounts", enabled: true, percentage: 30 },
      { id: "f5", name: "Pharmacy Discounts", category: "Discounts", enabled: true, percentage: 25 },
      { id: "f6", name: "Health Package Discounts", category: "Discounts", enabled: true, percentage: 25 },
      { id: "f7", name: "Wallet Credits", category: "Financial", enabled: true, percentage: 5 },
      { id: "f8", name: "Cashback Percentage", category: "Financial", enabled: true, percentage: 10 },
      { id: "f9", name: "Insurance Benefits", category: "Insurance", enabled: true },
      { id: "f10", name: "AI Health Assistant", category: "Digital", enabled: true, limit: 999 },
      { id: "f11", name: "Emergency Benefits", category: "Emergency", enabled: true },
      { id: "f12", name: "Priority Booking", category: "Appointments", enabled: true },
      { id: "f13", name: "Free Health Checkups", category: "Checkups", enabled: true, quantity: 4 },
      { id: "f14", name: "Referral Rewards", category: "Rewards", enabled: true, quantity: 500 },
    ],
  },
];

export const membershipAnalytics: MembershipAnalytics[] = [
  { tier: "silver", totalUsers: 42180, activeMembers: 38420, expiredMembers: 3760, renewals: 3120, upgrades: 840, revenue: 42117820, conversionRate: 18.4, renewalRate: 74.2 },
  { tier: "gold", totalUsers: 31490, activeMembers: 29840, expiredMembers: 1650, renewals: 2840, upgrades: 320, revenue: 78693510, conversionRate: 31.2, renewalRate: 84.6 },
  { tier: "platinum", totalUsers: 10650, activeMembers: 10420, expiredMembers: 230, renewals: 980, upgrades: 0, revenue: 53224350, conversionRate: 42.8, renewalRate: 91.4 },
];

export const membershipAuditLogs: MembershipAuditLog[] = [
  {
    id: "audit-1",
    action: "Plan Updated",
    planId: "plan-gold",
    planName: "Gold",
    version: 3,
    modifiedBy: "Super Admin",
    modifiedAt: "2024-06-01T10:30:00Z",
    previousConfig: { freeAppointments: 8, pharmacyDiscount: 10 },
    newConfig: { freeAppointments: 8, pharmacyDiscount: 15, insuranceBenefits: true },
    remarks: "Added insurance benefits per management directive",
  },
  {
    id: "audit-2",
    action: "Plan Updated",
    planId: "plan-gold",
    planName: "Gold",
    version: 2,
    modifiedBy: "Super Admin",
    modifiedAt: "2023-11-20T14:15:00Z",
    previousConfig: { freeAppointments: 12 },
    newConfig: { freeAppointments: 8 },
    remarks: "Reduced appointments due to cost optimization",
  },
  {
    id: "audit-3",
    action: "Plan Created",
    planId: "plan-silver",
    planName: "Silver",
    version: 1,
    modifiedBy: "Super Admin",
    modifiedAt: "2023-01-15T09:00:00Z",
    previousConfig: {},
    newConfig: { price: 999, freeAppointments: 6 },
    remarks: "Initial plan creation",
  },
];

export const userMemberships: UserMembership[] = [
  {
    userId: "u1",
    uhid: "VITA100245",
    name: "Lokesh Kumar",
    mobile: "9876543210",
    plan: membershipPlans[1],
    version: 2,
    purchaseDate: "2024-01-15",
    expiryDate: "2025-01-14",
    status: "active",
    benefitsAvailable: { freeAppointments: 8, followUps: 6, labDiscount: 20, diagnosticDiscount: 20, pharmacyDiscount: 15 },
    benefitsUtilized: { freeAppointments: 3, followUps: 1, labDiscount: 12, diagnosticDiscount: 8, pharmacyDiscount: 7 },
    benefitsRemaining: { freeAppointments: 5, followUps: 5, labDiscount: 8, diagnosticDiscount: 12, pharmacyDiscount: 8 },
    upgradeHistory: [{ date: "2024-01-15", fromPlan: "Silver", toPlan: "Gold", amount: 1500 }],
    renewalHistory: [{ date: "2023-01-15", plan: "Silver", amount: 999, expiryDate: "2024-01-14" }],
  },
  {
    userId: "u2",
    uhid: "VITA100246",
    name: "Priya Sharma",
    mobile: "9876543211",
    plan: membershipPlans[2],
    version: 1,
    purchaseDate: "2024-03-01",
    expiryDate: "2025-02-28",
    status: "active",
    benefitsAvailable: { freeAppointments: 24, followUps: 12, labDiscount: 30, diagnosticDiscount: 30, pharmacyDiscount: 25 },
    benefitsUtilized: { freeAppointments: 5, followUps: 2, labDiscount: 18, diagnosticDiscount: 12, pharmacyDiscount: 10 },
    benefitsRemaining: { freeAppointments: 19, followUps: 10, labDiscount: 12, diagnosticDiscount: 18, pharmacyDiscount: 15 },
    upgradeHistory: [],
    renewalHistory: [],
  },
];

export const featureUsageData = [
  { feature: "Free Doctor Appointments", silver: { total: 4, used: 2.4, remaining: 1.6 }, gold: { total: 8, used: 3.8, remaining: 4.2 }, platinum: { total: 24, used: 8.2, remaining: 15.8 } },
  { feature: "Follow-up Appointments", silver: { total: 2, used: 0.8, remaining: 1.2 }, gold: { total: 6, used: 2.1, remaining: 3.9 }, platinum: { total: 12, used: 3.4, remaining: 8.6 } },
  { feature: "Lab Discounts Utilized", silver: { total: 10, used: 6.8, remaining: 3.2 }, gold: { total: 20, used: 14.2, remaining: 5.8 }, platinum: { total: 30, used: 18.4, remaining: 11.6 } },
  { feature: "Diagnostic Discounts", silver: { total: 10, used: 5.2, remaining: 4.8 }, gold: { total: 20, used: 11.8, remaining: 8.2 }, platinum: { total: 30, used: 16.2, remaining: 13.8 } },
  { feature: "AI Assistant Usage", silver: { total: 10, used: 4.2, remaining: 5.8 }, gold: { total: 30, used: 18.4, remaining: 11.6 }, platinum: { total: 999, used: 84.2, remaining: 914.8 } },
  { feature: "Wallet Credits Earned", silver: { total: 100, used: 68, remaining: 32 }, gold: { total: 200, used: 142, remaining: 58 }, platinum: { total: 500, used: 284, remaining: 216 } },
];
