import type { SupportTicket } from "@/lib/types/ticket";

const HOUR = 60 * 60 * 1000;
const hoursAgo = (h: number) => new Date(Date.now() - h * HOUR).toISOString();
const daysAgo = (d: number) => hoursAgo(d * 24);

export const tickets: SupportTicket[] = [
  // Overdue P1s (open/in_progress, created > 1hr ago) — demonstrate SLA breach out of the box
  { id: "tk1", memberName: "Lokesh Kumar", email: "lokesh@email.com", contactNo: "9876543210", department: "Billing", panel: "hospital", panelEntityName: "Apollo Hospitals", issueDescription: "Duplicate charge on appointment booking, need urgent refund.", priority: "P1", status: "open", createdAt: hoursAgo(3) },
  { id: "tk2", memberName: "Dr. Arun Mehta", email: "arun.mehta@apollo.health", contactNo: "9876500011", department: "Technical Support", panel: "doctor", panelEntityName: "Apollo Hospitals", issueDescription: "Unable to access patient records from doctor console since morning.", priority: "P1", status: "in_progress", createdAt: hoursAgo(2) },
  { id: "tk3", memberName: "Ananya Krishnan", email: "ananya@email.com", contactNo: "9876543213", department: "Wallet & Credits", panel: "user", issueDescription: "Wallet credits not reflecting after bill upload, patient escalated on call.", priority: "P1", status: "open", createdAt: hoursAgo(4) },

  // P1 handled within SLA
  { id: "tk4", memberName: "Priya Sharma", email: "priya@email.com", contactNo: "9876543211", department: "Appointments", panel: "hospital", panelEntityName: "Fortis Healthcare", issueDescription: "Appointment slot booked twice for same doctor, needs immediate cancellation.", priority: "P1", status: "resolved", createdAt: hoursAgo(5), resolvedAt: hoursAgo(4.4) },
  { id: "tk5", memberName: "SRL Diagnostics Front Desk", email: "frontdesk@srl.health", contactNo: "9840011223", department: "Reports", panel: "laboratory", panelEntityName: "SRL Diagnostics", issueDescription: "Critical lab report upload failing for a cardiac patient.", priority: "P1", status: "resolved", createdAt: hoursAgo(8), resolvedAt: hoursAgo(7.5) },

  // P2 tickets — some overdue (> 1 day open), some within SLA
  { id: "tk6", memberName: "Rajesh Patel", email: "rajesh@email.com", contactNo: "9876543212", department: "Membership", panel: "user", issueDescription: "Gold membership benefits not applied on last two bills.", priority: "P2", status: "in_progress", createdAt: daysAgo(2) },
  { id: "tk7", memberName: "Mahesh Radiology Admin", email: "admin@maheshradiology.in", contactNo: "9820091122", department: "Reports", panel: "diagnostic", panelEntityName: "Mahesh Radiology", issueDescription: "Scan report PDFs not generating for patients booked yesterday.", priority: "P2", status: "open", createdAt: daysAgo(1.5) },
  { id: "tk8", memberName: "Dr. Kavitha Nair", email: "kavitha.nair@fortis.health", contactNo: "9876500022", department: "Technical Support", panel: "doctor", panelEntityName: "Fortis Healthcare", issueDescription: "Prescription module crashing when adding more than 5 medicines.", priority: "P2", status: "open", createdAt: hoursAgo(10) },
  { id: "tk9", memberName: "MedLife Pharmacy Manager", email: "manager@medlife.in", contactNo: "9848012233", department: "Pharmacy Orders", panel: "medical_store", panelEntityName: "MedLife Pharmacy", issueDescription: "Bulk bill upload tool rejecting valid bill PDFs with format error.", priority: "P2", status: "resolved", createdAt: daysAgo(3), resolvedAt: daysAgo(2.6) },
  { id: "tk10", memberName: "Sunita Reddy", email: "sunita@email.com", contactNo: "9876543215", department: "Appointments", panel: "hospital", panelEntityName: "KIMS Hospitals", issueDescription: "Unable to reschedule appointment, app shows generic error.", priority: "P2", status: "in_progress", createdAt: hoursAgo(14) },

  // P3 tickets — mostly within SLA, one aging
  { id: "tk11", memberName: "Mohammed Raza", email: "raza@email.com", contactNo: "9876543214", department: "Feedback", panel: "user", issueDescription: "Suggestion: add family member without re-uploading ID proof each time.", priority: "P3", status: "open", createdAt: hoursAgo(6) },
  { id: "tk12", memberName: "Care Plus Pharmacy Owner", email: "owner@carepluspharma.in", contactNo: "9840099887", department: "Onboarding", panel: "medical_store", panelEntityName: "Care Plus Pharmacy", issueDescription: "Need help mapping GST details correctly during onboarding.", priority: "P3", status: "open", createdAt: hoursAgo(20) },
  { id: "tk13", memberName: "LALS Path Labs Coordinator", email: "coordinator@lals.health", contactNo: "9811022334", department: "Reports", panel: "laboratory", panelEntityName: "LALS Path Labs", issueDescription: "Requesting bulk correction of patient age field on 6 old reports.", priority: "P3", status: "in_progress", createdAt: daysAgo(1) },
  { id: "tk14", memberName: "City Care Hospital Admin", email: "admin@citycare.health", contactNo: "9822011009", department: "Onboarding", panel: "hospital", panelEntityName: "City Care Hospital", issueDescription: "New hospital onboarding pending — doctor list bulk upload not going through.", priority: "P3", status: "open", createdAt: daysAgo(3) },
  { id: "tk15", memberName: "Dr. Ramesh Reddy", email: "ramesh.reddy@kims.health", contactNo: "9876500033", department: "Technical Support", panel: "doctor", panelEntityName: "KIMS Hospitals", issueDescription: "Doctor rating shown incorrectly on public profile page.", priority: "P3", status: "resolved", createdAt: daysAgo(4), resolvedAt: daysAgo(3.2) },
  { id: "tk16", memberName: "Dr. Sunita Patel", email: "sunita.patel@apollo.health", contactNo: "9876500044", department: "Technical Support", panel: "doctor", panelEntityName: "Apollo Hospitals", issueDescription: "Calendar sync delayed by a few minutes during peak hours.", priority: "P3", status: "resolved", createdAt: daysAgo(5), resolvedAt: daysAgo(4.5) },

  // Additional mix for volume/filters
  { id: "tk17", memberName: "Apollo Pharmacy Manager", email: "manager@apollopharmacy.in", contactNo: "9848055667", department: "Pharmacy Orders", panel: "medical_store", panelEntityName: "Apollo Pharmacy", issueDescription: "Medicine bill upload stuck in processing state for over an hour.", priority: "P1", status: "resolved", createdAt: hoursAgo(30), resolvedAt: hoursAgo(29.2) },
  { id: "tk18", memberName: "Thyrocare Regional Head", email: "regional@thyrocare.in", contactNo: "9820033445", department: "Reports", panel: "laboratory", panelEntityName: "Thyrocare", issueDescription: "Need API access logs for last week's report uploads.", priority: "P3", status: "open", createdAt: hoursAgo(2) },
  { id: "tk19", memberName: "Medall Diagnostic Center Admin", email: "admin@medall.in", contactNo: "9840077889", department: "Onboarding", panel: "diagnostic", panelEntityName: "Medall Diagnostic Center", issueDescription: "Diagnostic package pricing not reflecting latest update.", priority: "P2", status: "open", createdAt: hoursAgo(6) },
  { id: "tk20", memberName: "MedPlus Clinic Front Desk", email: "frontdesk@medplus.health", contactNo: "9822044556", department: "Billing", panel: "hospital", panelEntityName: "MedPlus Clinic", issueDescription: "Suspended hospital status blocking legitimate patient records access.", priority: "P1", status: "in_progress", createdAt: hoursAgo(1) },
  { id: "tk21", memberName: "Fortis Healthcare Admin", email: "admin@fortis.health", contactNo: "9822099001", department: "Membership", panel: "hospital", panelEntityName: "Fortis Healthcare", issueDescription: "Hospital-wise discount override not applying for Gold tier.", priority: "P2", status: "resolved", createdAt: daysAgo(6), resolvedAt: daysAgo(5.5) },
  { id: "tk22", memberName: "KIMS Hospitals Admin", email: "admin@kims.health", contactNo: "9822088990", department: "Wallet & Credits", panel: "hospital", panelEntityName: "KIMS Hospitals", issueDescription: "Referral credits not crediting to referrer wallet.", priority: "P3", status: "in_progress", createdAt: daysAgo(1.5) },
  { id: "tk23", memberName: "Sunita Reddy", email: "sunita@email.com", contactNo: "9876543215", department: "Appointments", panel: "user", issueDescription: "Wants clarification on appointment cancellation policy.", priority: "P3", status: "resolved", createdAt: daysAgo(2), resolvedAt: daysAgo(1.9) },
  { id: "tk24", memberName: "Rahul Gupta", email: "rahul@vita.health", contactNo: "9876500099", department: "Technical Support", panel: "user", issueDescription: "Admin dashboard export button unresponsive intermittently.", priority: "P2", status: "open", createdAt: hoursAgo(28) },
];
